// <auto-generated />
using System;
using CalendarUI.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalendarUI.Migrations
{
    [DbContext(typeof(CalendarContext))]
    partial class CalendarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalendarUI.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Attendees")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DateTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de7c6f81-68bc-45cb-8ec8-60f6aa0250b0"),
                            Attendees = "Fal J, Mark Z, Jeff Z",
                            DateTime = new DateTime(2021, 10, 15, 23, 12, 49, 534, DateTimeKind.Local).AddTicks(4987),
                            Description = "Interview",
                            Organizer = "Amir"
                        },
                        new
                        {
                            Id = new Guid("daec16b2-025f-4401-9e38-c4379f62ec46"),
                            Attendees = "A J, D S",
                            DateTime = new DateTime(2021, 10, 25, 23, 12, 49, 540, DateTimeKind.Local).AddTicks(3542),
                            Description = "Meeting",
                            Organizer = "Javad"
                        },
                        new
                        {
                            Id = new Guid("ebc22679-c0e4-4d94-acb0-68286270e1a5"),
                            Attendees = "Fin J, Dar S",
                            DateTime = new DateTime(2021, 11, 4, 23, 12, 49, 540, DateTimeKind.Local).AddTicks(3641),
                            Description = "Int with Fin",
                            Organizer = "Ali"
                        },
                        new
                        {
                            Id = new Guid("96059c0b-737d-4789-8b49-f78eb421478a"),
                            Attendees = "John D, Ali S",
                            DateTime = new DateTime(2021, 11, 24, 23, 12, 49, 540, DateTimeKind.Local).AddTicks(3666),
                            Description = "Meeting with Ali S",
                            Organizer = "Smith"
                        },
                        new
                        {
                            Id = new Guid("ec5e460e-0a48-4f7f-ae1a-963dca87c0ab"),
                            Attendees = "Smith J, Sun S",
                            DateTime = new DateTime(2021, 12, 14, 23, 12, 49, 540, DateTimeKind.Local).AddTicks(3718),
                            Description = "Interview with Smith",
                            Organizer = "John"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
